version: "3.7"
services:
  db:
    image: mirror.gcr.io/mariadb:11.8.1-ubi9-rc
    container_name: database
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password  # rootユーザのパスワード
      MYSQL_DATABASE: db_local       # WordPress用データベース名
      MYSQL_USER: wp_user            # WordPress用データベース接続ユーザ名
      MYSQL_PASSWORD: password       # WordPress用データベース接続パスワード

  WordPress:
    image: mirror.gcr.io/wordpress:6.8.1-php8.1-apache
    container_name: wordpress
    restart: always
    depends_on:
      - db
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wp_user
      WORDPRESS_DB_PASSWORD: password  
      WORDPRESS_DB_NAME: db_local
      WORDPRESS_DEBUG: 1
    volumes:
      - ./html:/var/www/html